"""add user table
Revision ID: 66a73707be3f
Revises: 561e979cf32a
Create Date: 2026-01-03 21:58:37.713233
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '66a73707be3f'
down_revision = '561e979cf32a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('externalId', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('onboardingStatus', sa.Enum('NEW', 'DETAILS_COMPLETED', 'RULES_ACCEPTED', 'FINISHED', name='onboardingstatusenum'), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('externalId')
    )
    op.alter_column('fixture', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('fixture', 'fixtureUrl',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('fixture', 'createdAt',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('fixture', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixture', 'updatedAt',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('fixture', 'createdAt',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('fixture', 'fixtureUrl',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('fixture', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_table('user')
    # ### end Alembic commands ###
